### PR TITLE
Search packages in all catalogs

### LINKED ISSUE #346: search chart inside all catalogs
The search bar only look inside the current catalog.
I guess it's more usefull to search inside all catalogs directly.

image

Maybe this mean that the search bar should be moved a little higher.

### PR DESCRIPTION
**Pull request by PaulGehin**
Resolves #346

### CODE REVIEW

**Comment by PaulGehin** [comment]
I implemented the search.
A point to improve would be to be able to differentiate packages with the same name (for example vscode or jupyter).

Would it be worth adding a tag with the catalog id on the card?

**Comment by garronej** [comment]
Thank you! LGTM (except a usless assert statement that needs to be removed but I'll take care of it)

**Comment by garronej** [comment]
> Would it be worth adding a tag with the catalog id on the card?  

Yes, this would be nice! You could use the `<Tag />` component.

**Comment by garronej** [comment]
@PaulGehin just to let you know, [this](https://github.com/InseeFrLab/onyxia-web/commit/9a7680107f22e41b75d99ff7aa1c230238c0b410) are small refactor I made on your PR.

**Pull request merged**
