### PR TITLE
359 highlighted charts

### LINKED ISSUE #359: highligted charts
This feature help Onyxia Admins to highlight some chart inside a catalog.

When a user is on the catalog page : 
image

some charts are visible by default and some are not.
Onyxia-API shows this on the catalog endpoint with highlightedCharts attribut on each catalog.

This is not yet used by Onyxia-web. 
The onyxia-web env var should be deprecated because api send this information for each catalog now : 

```yaml
# OPTIONAL, Highlight some packages of the default catalog. It can also be used as a way of defining an ordering.
# For this result: https://user-images.githubusercontent.com/6702424/152658921-bb6e87ba-a9e0-4cbb-841c-baafd34f50ef.png
# you would use 
# HIGHLIGHTED_PACKAGES: |
# 	[ "rstudio", "jupyter", "ubuntu", "postgres", "code" ]
# The entries should correspond to the chart name, example with rstudio: https://github.com/InseeFrLab/helm-charts-datascience/blob/09dd37aca108423cb337a07be6a58f1cda381aa4/chart
# case doesn’t matter if an entry is not present in the catalog it doesn't matter.
# If not defined you'll directly get a view showing all available packages: https://user-images.githubusercontent.com/6702424/152658975-f3931d3f-b6bd-4b1c-a0c1-b35111ef4239.png
REACT_APP_HIGHLIGHTED_PACKAGES=
```

I think this new list of highligted charts must be an exact match.

### PR DESCRIPTION
**Pull request by alainds**
closes #359

### CODE REVIEW

**Comment by alainds** [comment]
Warning : I did a few tests but I am not very confident because I didn't sure that I tested all the use cases. and I didn't do any unit tests on this little breaking change so check my changes. 
PS : I wanted to do something more elegant with less duplication but I preferred keep the existing logic.

**Comment by garronej** [comment]
> I did a few tests but I am not very confident because I am not sure that I tested all the use cases.  

Don't worry it's no big deal anyway?  

> PS : I wanted to do something more elegant with less duplication but I preferred to keep the existing logic.  

What do you mean?

**Comment by alainds** [comment]
> > I did a few tests but I am not very confident because I am not sure that I tested all the use cases.
> 
> Don't worry it's no big deal anyway?
> 
> > PS : I wanted to do something more elegant with less duplication but I preferred to keep the existing logic.
> 
> What do you mean?

No I mean I just replace "highlightedPackages" which was taken from the store by the "highlightedCharts" from the API in all the places where highlightedPackages were used. But maybe we could do something more elegant because there are some duplications in catalogExplorer.ts and I added some code that I was not very proud of, but I think it's OK.

**Comment by garronej** [comment]
Ok,   
Is this code beeing present twice what you are reffering to when you say there is code duplication?  
```typescript
            const highlightedCharts =
                catalogs?.find(catalog => catalog.id === selectedCatalogId)
                    ?.highlightedCharts || [];
```  
If yes, I'm willing to let if fly, I think it's ok.

**Comment by alainds** [comment]
> 



> Is this code beeing present twice what you are reffering to when you say there is code duplication?

yes, that's it.

**Comment by garronej** [comment]
Ok top, I'll will have merged by monday. (I have to update the migration guide)

**Pull request merged**
