### PR TITLE
Dynamically adding extra external links to sidebar

### PR DESCRIPTION
**Pull request by dmoreira97DLTT**
With this PR we want to integrate a new environment variable that lets a user define extra links to be rendered in the sidebar. 

This environment variable has a `json` format. It will define each entry by its name, icon, url, and translations for English and French: 
```json
REACT_APP_SIDEBAR_LINKS  = |
{
    "links": [
      { 
        "name": "myDataVisualizationTool",
        "iconId": "SsidChart",
        "url": "apache-superset",
        "nameEN": "Data Visualization Tool",
        "nameFR": "Outil de visualisation de données"
      },
      {
        "name": "myDataCatalog",
        "iconId": "MenuBookOutlined",
        "url": "ckan",
        "nameEN": "My Data Catalog",
        "nameFR": "Mes catalogue de données"
      }
    ]
}
```

After the variable is imported it will map each content to its file location and be rendered, obtaining a sidebar as such:

image

Glad to hear your feedback 😃

### CODE REVIEW

**Comment by olevitt** [comment]
Thanks !
@dmoreira97DLTT small remark at first glance : you deleted the `yarn.lock` file that is supposed to be versionned
@garronej I added you as a reviewer

**Comment by dmoreira97DLTT** [comment]
Thanks, the `yarn.lock` has been rebuilt 👍

**Comment by garronej** [comment]
Hi @dmoreira97DLTT,  
Thank you very much for taking the time to submit a PR, your work is much appreciated and this is a good feature.  
Now, for optimal future collaboration:  
- Be careful to keep the DIFF as small as possible, only the relevant files must be changed.  
- In this project, every entity must be typed. When a serialized object enters the system, it must be parsed by a function which return type is precisely describing the expected form of the object.  
In this instance, there is a high probability of the user making a mistake when filling in the value. It's a good idea to validate the object at runtime just after parsing it. This way, if it's malformed, the user knows it early.  
- Try to respect the naming convention as much as possible. (example: ~~sidebar~~, leftbar)  
- If you add options, they must me documented.  
- We should not restrict things to just french and english.  

Now for points directly related to this PR:   
- We can't include all 1900 Material icon in the bundle just for this feature, it's 4MB, the equivalent of 2 Temple OS.  
  The way to go would be to modify [this component](https://github.com/InseeFrLab/onyxia-ui/blob/main/src/Icon.tsx) to make it capable of downloading any [material icon](https://mui.com/components/material-icons/) at runtime, it's a complex task, PR are welcome but, in the meantime, only already available icon id is accepted.  
- You introduced two ENVs one for the links and one for the domain. While agree that keeping things as DRY as possible is very important, in this particular instance using `domain` restricts the links that can be provided (what if they aren't from the same domain?) and it induces an extra level of complexity to an already hard to get right variable.  

You can find [here](https://github.com/InseeFrLab/onyxia-web/commit/b21196b99477a91a0c4e31ebd169666d5f830ef6) the commit where I address all those points.  

Best,

**Comment by garronej** [comment]
it's now possible to configure the headers links as well

**Pull request merged**
